version: '3.7'

services:
  main:
    container_name: course_main
    build:
        context: .
        target: development
    volumes:
        - .:/usr/src/app
        - /usr/src/app/node_modules
    ports:
        - ${SERVER_PORT}:${SERVER_PORT}
        - 3001:3001
    command: npm run start:dev
    env_file:
        - .env